### PR TITLE
Random Fixes

### LINKED ISSUE #101: Bug when logging in as jenny with cleared cache and cookies
1) Clear cache and cookies
2) Log in as jenny
3) See the below console errors as the screen is stuck on te loading page
4) Unable to open menu

P.S. May be just because jenny was artificially seeded

image

### LINKED ISSUE #102: Gray line in DropGem semicircle
anyone else sees this
image

### PR DESCRIPTION
**Pull request by sebastiantoh**
Resolves https://github.com/hansel-app/hansel/issues/101

Resolves https://github.com/hansel-app/hansel/issues/102

### CODE REVIEW

File: frontend/src/store/modules/gems.ts [hunk 1]
```diff
@@ -24,18 +24,18 @@ export interface GemsState {
...
-});
+};
 
 const gemsModule: Module<GemsState, RootState> = {
-  state: initialState,
+  state: { ...initialState },
   mutations: {
     resetGemsStore(state) {
-      Object.assign(state, initialState);
+      Object.assign(state, JSON.parse(JSON.stringify(initialState)));
```
Comment (ianyong) [inline frontend/src/store/modules/gems.ts]: What if we used [Lodash's `cloneDeep`](https://lodash.com/docs/#cloneDeep) instead? This isn't very obvious.

Comment (sebastiantoh) [reply frontend/src/store/modules/gems.ts]: was thinking it would be a bit overkil to add lodash just for this haha. but sure, i'll make the change!

File: frontend/src/components/SemiCircleBg.vue [hunk 2]
```diff
@@ -19,7 +19,7 @@ export default defineComponent({
   position: relative;
   height: 45vh;
   z-index: -1;
-  overflow-x: hidden;
+  overflow: hidden;
```
Comment (sebastiantoh) [inline frontend/src/components/SemiCircleBg.vue:22]: @ming-00 this line fixes it!

**Review by ianyong — APPROVED** [review]
LGTM!
