### PR TITLE
Fix registration

### LINKED ISSUE #114: Register does not work
image

### PR DESCRIPTION
**Pull request by ianyong**
Resolves #114.

### CODE REVIEW

File: backend/internal/adapters/secondary/repositories/user.go [hunk 1]
```diff
@@ -53,7 +53,7 @@ func (r *userRepository) GetUsersByIds(ids []int64) (map[int64]users.User, error
 }
 
 func (r *userRepository) GetByUsername(username string) (*users.User, error) {
-	sql, _, _ := qb.From("users").Where(goqu.C("username").Eq(username)).ToSQL()
+	sql, _, _ := qb.From(goqu.T("users")).Where(goqu.C("username").Eq(username)).ToSQL()
```
Comment (sebastiantoh) [inline backend/internal/adapters/secondary/repositories/user.go:56]: :o is this necessary? I think some of the other stuff i wrote didn't have this

Comment (ianyong) [reply backend/internal/adapters/secondary/repositories/user.go:56]: Shouldn't be, but just in case HAHA

**Review by sebastiantoh — APPROVED** [review]
lgtm!
